# Generated by Django 2.2.7 on 2021-04-24 20:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='person',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persontranslation',
            name='professional_history',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persontranslation',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
