# Generated by Django 2.2.7 on 2021-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_sitesettingstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
    ]
