# Generated by Django 2.2.7 on 2021-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210503_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
    ]
