# Generated by Django 2.2.7 on 2021-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesettings_twitter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploads/logo/'),
        ),
    ]
