# Generated by Django 2.2.7 on 2021-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sitesettings_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumtranslation',
            name='main_image',
        ),
        migrations.AddField(
            model_name='album',
            name='main_image',
            field=models.ImageField(null=True, upload_to='uploads/album/album/%Y/%m/%d/'),
        ),
    ]
