# Generated by Django 2.2.7 on 2021-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettingstranslation_event_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='tel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
