# Generated by Django 2.2.7 on 2021-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210510_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtranslation',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
