# Generated by Django 2.2.7 on 2021-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210510_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(to='main.PostCategory'),
        ),
    ]
