# Generated by Django 2.2.7 on 2021-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210510_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagedata',
            name='location_map_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
