# Generated by Django 2.2.7 on 2021-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_regionaloffice_regionalofficetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaloffice',
            name='logo',
            field=models.ImageField(upload_to='uploads/regional_office/'),
        ),
    ]
