# Generated by Django 2.2.7 on 2021-05-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210512_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
