# Generated by Django 2.2.7 on 2021-05-13 10:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('karakalpakstan', 'Karakalpakstan'), ('kashkadarya', 'Kashkadarya'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoi', 'Navoi'), ('samarkand', 'Samarkand'), ('surkhandarya', 'Surkhandarya'), ('syrdarya', 'Syrdarya'), ('tashkent_city', 'Tashkent city'), ('tashkent_region', 'Tashkent region')], max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('file', models.FileField(upload_to='uploads/application/%Y/%m/%d')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('reviewing', 'Reviewing'), ('resolving', 'Resolving'), ('rejected', 'Rejected')], default=('accepted', 'Accepted'), max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
