# Generated by Django 2.2.7 on 2021-05-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210514_0055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcategorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postcategorytranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='PostCategoryTranslation',
        ),
    ]
