# Generated by Django 2.2.7 on 2021-05-14 12:19

import ckeditor.fields
from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210514_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_image',
            field=models.ImageField(null=True, upload_to='uploads/organization/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organizationtranslation',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtranslation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtranslation',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizationtranslation',
            name='head_of_office',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationtranslation',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
