# Generated by Django 2.2.7 on 2021-05-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210514_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/application/%Y/%m/%d'),
        ),
    ]
