# Generated by Django 2.2.7 on 2021-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210515_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtranslation',
            name='short_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
