# Generated by Django 2.2.7 on 2021-05-15 12:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_albumtranslation_short_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/media/%Y/%m/%d')),
                ('video_file', models.FileField(upload_to='uploads/media/%Y/%m/%d')),
                ('youtube_embed_link', models.URLField()),
                ('audio_file', models.FileField(upload_to='uploads/media/%Y/%m/%d')),
                ('audio_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'media Translation',
                'db_table': 'main_media_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='albumcategorytranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='albumcategorytranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='albumitem',
            name='album',
        ),
        migrations.AlterUniqueTogether(
            name='albumtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='albumtranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title',
        ),
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('photo', 'Photo')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumCategory',
        ),
        migrations.DeleteModel(
            name='AlbumCategoryTranslation',
        ),
        migrations.DeleteModel(
            name='AlbumItem',
        ),
        migrations.DeleteModel(
            name='AlbumTranslation',
        ),
        migrations.AddField(
            model_name='mediatranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.Media'),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Media'),
        ),
        migrations.AlterUniqueTogether(
            name='mediatranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
