# Generated by Django 2.2.7 on 2021-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210515_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mediaobject',
            name='audio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaobject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mediaobject',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='mediaobject',
            name='youtube_embed_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
