# Generated by Django 2.2.7 on 2021-05-15 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210515_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/media/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'ogg', 'mkv', 'webm'])]),
        ),
    ]
