# Generated by Django 2.2.7 on 2021-05-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210515_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaobject',
            old_name='youtube_embed_link',
            new_name='youtube_video_id',
        ),
    ]
