# Generated by Django 2.2.7 on 2021-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210515_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaobject',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
