# Generated by Django 2.2.7 on 2021-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210516_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AddField(
            model_name='person',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
