# Generated by Django 2.2.7 on 2021-05-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210516_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
