# Generated by Django 2.2.7 on 2021-05-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_static_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
