# Generated by Django 2.2.7 on 2021-05-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210516_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('people_count', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
