# Generated by Django 2.2.7 on 2021-05-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_to_send_letters',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('reviewing', 'Reviewing'), ('resolving', 'Resolving'), ('rejected', 'Rejected')], default='accepted', max_length=255),
        ),
    ]
