# Generated by Django 2.2.7 on 2021-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210516_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='email_to_send_letters',
            new_name='email_sender_address',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_sender_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
