# Generated by Django 2.2.7 on 2021-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_sitesettings_email_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaobject',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='release_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
