# Generated by Django 2.2.7 on 2021-05-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20210517_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaobject',
            old_name='artist',
            new_name='audio_artist',
        ),
        migrations.RenameField(
            model_name='mediaobject',
            old_name='genre',
            new_name='audio_genre',
        ),
        migrations.RenameField(
            model_name='mediaobject',
            old_name='release_date',
            new_name='audio_release_date',
        ),
    ]
