# Generated by Django 2.2.7 on 2021-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20210517_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagedata',
            options={'verbose_name': 'About page data', 'verbose_name_plural': 'About page data'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagedatatranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'About page data Translation'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='bannertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Banner Translation'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventorder',
            options={'verbose_name': 'Event order', 'verbose_name_plural': 'Event orders'},
        ),
        migrations.AlterModelOptions(
            name='eventtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Event Translation'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Medias'},
        ),
        migrations.AlterModelOptions(
            name='mediaobject',
            options={'verbose_name': 'Media object', 'verbose_name_plural': 'Media objects'},
        ),
        migrations.AlterModelOptions(
            name='mediatranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Media Translation'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationcategory',
            options={'verbose_name': 'Organization category', 'verbose_name_plural': 'Organization categories'},
        ),
        migrations.AlterModelOptions(
            name='organizationcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Organization category Translation'},
        ),
        migrations.AlterModelOptions(
            name='organizationtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Organization Translation'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='persontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Person Translation'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post category', 'verbose_name_plural': 'Post categories'},
        ),
        migrations.AlterModelOptions(
            name='postcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Post category Translation'},
        ),
        migrations.AlterModelOptions(
            name='postfile',
            options={'verbose_name': 'Post file', 'verbose_name_plural': 'Post files'},
        ),
        migrations.AlterModelOptions(
            name='postfiletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Post file Translation'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post image', 'verbose_name_plural': 'Post images'},
        ),
        migrations.AlterModelOptions(
            name='posttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Post Translation'},
        ),
        migrations.AlterModelOptions(
            name='regionaloffice',
            options={'verbose_name': 'Regional office', 'verbose_name_plural': 'Regional offices'},
        ),
        migrations.AlterModelOptions(
            name='regionalofficetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Regional office Translation'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AlterModelOptions(
            name='sitesettingstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Site settings Translation'},
        ),
        migrations.AlterModelOptions(
            name='static',
            options={'verbose_name': 'Static page', 'verbose_name_plural': 'Static pages'},
        ),
        migrations.AlterModelOptions(
            name='statictranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Static page Translation'},
        ),
        migrations.AlterModelOptions(
            name='typo',
            options={'verbose_name': 'Typo', 'verbose_name_plural': 'Typos'},
        ),
        migrations.AddField(
            model_name='post',
            name='posting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
