# Generated by Django 2.2.7 on 2021-05-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20210517_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
    ]
