# Generated by Django 2.2.7 on 2021-05-17 22:13

from django.db import migrations, models
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_organizationcategory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('month', partial_date.fields.PartialDateField()),
                ('accepted', models.PositiveIntegerField(null=True)),
                ('on_process', models.PositiveIntegerField(null=True)),
                ('solved', models.PositiveIntegerField(null=True)),
                ('not_solved', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='organizationcategory',
            options={'ordering': ['order'], 'verbose_name': 'Organization category', 'verbose_name_plural': 'Organization categories'},
        ),
    ]
