# Generated by Django 2.2.7 on 2021-05-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20210518_0313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='StatisticalData',
        ),
    ]
