# Generated by Django 2.2.7 on 2021-05-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20210518_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticaldata',
            name='month',
        ),
    ]
