# Generated by Django 2.2.7 on 2021-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_statisticaldata_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldata',
            name='month',
            field=models.DateField(null=True),
        ),
    ]
