# Generated by Django 2.2.7 on 2021-05-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_statisticaldata_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticaldata',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='statisticaldata',
            name='not_solved',
        ),
        migrations.RemoveField(
            model_name='statisticaldata',
            name='on_process',
        ),
        migrations.RemoveField(
            model_name='statisticaldata',
            name='solved',
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='helpline_accepted',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='helpline_not_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='helpline_on_process',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='helpline_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='online_accepted',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='online_not_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='online_on_process',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='online_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='oral_accepted',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='oral_not_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='oral_on_process',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='oral_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='written_accepted',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='written_not_solved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='written_on_process',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statisticaldata',
            name='written_solved',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
