# Generated by Django 2.2.7 on 2021-05-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20210518_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingstranslation',
            name='work_hours',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
