# Generated by Django 2.2.7 on 2021-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_sitesettingstranslation_work_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticaldata',
            options={'verbose_name': 'Statistical data', 'verbose_name_plural': 'Statistical datas'},
        ),
        migrations.RemoveField(
            model_name='aboutpagedatatranslation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutpagedatatranslation',
            name='helpline',
        ),
        migrations.RemoveField(
            model_name='aboutpagedatatranslation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='aboutpagedata',
            name='email1',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagedata',
            name='email2',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagedata',
            name='email3',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagedata',
            name='helpline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagedata',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
