# Generated by Django 2.2.7 on 2021-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20210601_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_regions_filter',
            field=models.BooleanField(default=False),
        ),
    ]
