# Generated by Django 2.2.7 on 2021-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_organization_display_regions_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='display_regions_filter',
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='display_regions_filter',
            field=models.BooleanField(default=False),
        ),
    ]
