# Generated by Django 2.2.7 on 2021-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20210608_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posting_date', '-time_added'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='posting_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
