# Generated by Django 2.2.7 on 2021-06-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20210609_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posting_date'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
