# Generated by Django 2.2.7 on 2021-06-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20210614_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
