# Generated by Django 2.2.7 on 2021-09-28 08:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20210615_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyindicator',
            options={'ordering': ['order'], 'verbose_name': 'Key indicator', 'verbose_name_plural': 'Key indicators'},
        ),
        migrations.AlterModelOptions(
            name='keyindicatortranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Key indicator Translation'},
        ),
        migrations.AlterModelOptions(
            name='usefullink',
            options={'ordering': ['order'], 'verbose_name': 'Useful link', 'verbose_name_plural': 'Useful links'},
        ),
        migrations.AlterModelOptions(
            name='usefullinktranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Useful link Translation'},
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Application content'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/application/%Y/%m/%d', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('bukhara', 'Bukhara'), ('fergana', 'Fergana'), ('jizzakh', 'Jizzakh'), ('karakalpakstan', 'Karakalpakstan'), ('kashkadarya', 'Kashkadarya'), ('khorezm', 'Khorezm'), ('namangan', 'Namangan'), ('navoi', 'Navoi'), ('samarkand', 'Samarkand'), ('surkhandarya', 'Surkhandarya'), ('syrdarya', 'Syrdarya'), ('tashkent_city', 'Tashkent city'), ('tashkent_region', 'Tashkent region')], max_length=255, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bannertranslation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
