# Generated by Django 2.2.7 on 2021-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20210928_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(upload_to='uploads/banner/'),
        ),
    ]
