# Generated by Django 2.2.7 on 2021-06-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
